name: 中青看点-自动阅读1

on:
  workflow_dispatch:

  schedule:
     - cron: '20 */3 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      YOUTH_READ_2: ${{ secrets.YOUTH_READ_2 }}
      YOUTH_READ_3: ${{ secrets.YOUTH_READ_3 }}
      YOUTH_READ_4: ${{ secrets.YOUTH_READ_4 }}
      YOUTH_READ_5: ${{ secrets.YOUTH_READ_5 }}
      YOUTH_READ_6: ${{ secrets.YOUTH_READ_6 }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点一】'
        if: env.YOUTH_READ      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
      - name: '运行 【中青看点二】'
        if: env.YOUTH_READ_2      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_2 }}
      - name: '运行 【中青看点三】'
        if: env.YOUTH_READ_3      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_3 }}
      - name: '运行 【中青看点四】'
        if: env.YOUTH_READ_4      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_4 }}
      - name: '运行 【中青看点五】'
        if: env.YOUTH_READ_5      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_5 }}
      - name: '运行 【中青看点六】'
        if: env.YOUTH_READ_6      
        run: |
          node Youth/Youth_AutoRead.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_6 }}
