name: Curtin-闪挣

on:
  workflow_dispatch:

  schedule:
     - cron: '0,7,14,21,28,35,42,49,56 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【闪挣】'   
        run: |
          node SZ/sz.js
        env:
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
